### ISSUE TITLE
CCDDExpose segfaults if filename not provided

### ISSUE THREAD

**Issue by ryanjthomas** [xtachx/CCDDrone#10]
**Summary**
Running CCDDExpose without an output filename causes a segmentation fault.

**Steps to reproduce**
Run CCDDExpose without an output filename argument (e.g. "./CCDDExpose 5"). 

**Expected Result**
CCDDExpose runs taking an image saved as Image.fits

**Actual Results**
CCDDExpose crashes with a segmentation fault.

**Backtrace from GDB during crash**
>#0  0x00007ffff669dff1 in __strlen_sse2_pminub () from /lib64/libc.so.6
#1  0x00007ffff6ed23e4 in std::string::assign(char const*) () from /lib64/libstdc++.so.6
#2  0x00000000004011bf in operator= (__s=<optimized out>, this=0x7fffffffdc50)
    at /usr/include/c++/4.8.2/bits/basic_string.h:555
#3  main (argc=<optimized out>, argv=0x7fffffffe1c8) at /home/damic/CCDDrone/CCDDExpose.cpp:42

**Other notes**
From the documentation on std::string::assign:

> If s does not point to an array long enough, or if the range specified by [first,last) is not valid, it causes undefined behavior.

Hence the segfault.

**Comment by xtachx** [comment]
Fixed. I made a mistake with the argc before.
