### ISSUE TITLE
Loading a new firmware file using CCDDApplyNewSettings resets the image size

### ISSUE THREAD

**Issue by ryanjthomas** [xtachx/CCDDrone#12]
### Issue description
Loading a new firmware file using CCDDApplyNewSettings resets the image size.

### Steps to reproduce the issue

1.  Use CCDDApplyNewSettings to load a different configuration file from the one currently loaded.
2. You can see on the oscilloscope that the number of columns read per row decreases to a very small number (~10)

I haven't actually tried taking an image in this configuration, so I don't know if that would work (since the image size is set during the PrepareAndExposeCCD, it should).

### Expected result?
Applying a new sequencer also sets the image size from the configuration file. 

Adding "pArcDev->SetImageSize(this->CCDParams.dRows,this->CCDParams.dCols);" to 
LeachController::ApplyNewSequencer achieves this result (although ApplyNewSettings should probably set the image size directly since that can be changed in the configuration file without altering the sequencer).

**Comment by xtachx** [comment]
Fixed
