### ISSUE TITLE
Control clocks (hi and lo) on serial registers 1 and 2 independently

### ISSUE THREAD

**Issue by inutilbasura** [xtachx/CCDDrone#15]
We should have OG, SW, DG, RG and TG broken up into groups for serial register 1 and 2, i.e., OG1, OG2, SW1, SW2, etc.

Every clock (hi and lo) and bias board output that is used to control the CCD should be set independently in the configuration file.

**Comment by xtachx** [comment]
On UW1 boards, the lines are physically separated by U and L instead of SR1 and SR2, so the settings for SR1 are used for both U and L. Is this ok?

**Comment by inutilbasura** [comment]
In this case the 1s should control L and the 2s control U.

Cheers,

Alvaro

**Comment by xtachx** [comment]
This leads to inconsistencies like there is only one TG for example. What happens to these lines ?

Envoyé de mon iPhone

Le 3 mars 2020 à 2:31 PM, inutilbasura <notifications@github.com> a écrit :

﻿In this case the 1s should control L and the 2s control U.

Cheers,

Alvaro

**Comment by inutilbasura** [comment]
Then it is controlled by TG1, and TG2 does nothing.

We need a document summarizing all these choices.

Cheers,

Alvaro

**Comment by xtachx** [comment]
Added functionality with 1f4a7156666d408d1582da23ccf95185feeedd15
