### ISSUE TITLE
RG should fire at the beginning of every pixel

### ISSUE THREAD

**Issue by inutilbasura** [xtachx/CCDDrone#17]
Please make RG fire before every pixel in the default version of the sequencer. Otherwise, default version of sequencer will not work with "DES" option.

**Comment by xtachx** [comment]
What should the width of this RG be? (not variable)

**Comment by inutilbasura** [comment]
Can it be set in the config file?

Why do the RGs between DES and SK options need to be different?

Cheers,

Alvaro

**Comment by xtachx** [comment]
Added with SuperSequencer update https://github.com/xtachx/CCDSequencer/commit/633fd4418f13a1b9f7ea70f2d09a4c28de438640
