### ISSUE TITLE
New version of SRS integrated with RPC does not change the voltages on the SRS power supply

### ISSUE THREAD

**Issue by alexanderpiers** [xtachx/CCDDrone#20]
When running either CCDDApplyNewSettings ro CCDDEraseProcedure, the power output by the SRS supply never changes, no matter what Vsub or erase procedure components are set to.

**Comment by xtachx** [comment]
Ouch! Thats a nasty bug.

Should be fixed with https://github.com/xtachx/DAMIC_CryoController/commit/79e97798b9bc690de147ece55c08207b08140aec
