### ISSUE TITLE
Please add RUNID to FITS header

### ISSUE THREAD

**Issue by inutilbasura** [xtachx/CCDDrone#4]
Please add the image number as "RUNID" in the FITS header. Also "EXTID" for the CCD number. For single-CCD systems default value should be 1.

**Comment by xtachx** [comment]
I do not understand, can you please clarify:

1. Where does the "image number" come from? If this is the number at the end of a file name, then what happens if there is no number there? 

2. Where should EXTID be defined?

**Comment by xtachx** [comment]
Insufficient info to continue. Closing issue.
