### ISSUE TITLE
VDD doesn't turn back on if expose time too short

### ISSUE THREAD

**Issue by ryanjthomas** [xtachx/CCDDrone#9]
When running CCDDExpose with short exposure times (e.g. 1 second, but I suspect it would happen with any exposure < 3 seconds), VDD is switched off and never gets turned back on again.

**Comment by xtachx** [comment]
The reason is that the  VDD ON script sees how many seconds are left and turns the VDD on if the timer goes below 2s. If you give an exposure value thats lower than 2s, this condition is never met. I have fixed this as a part of the upgrade where I have separated the two VDD lines.
